import { Grid, Typography, Box, Theme, Divider } from "@mui/material";
import { makeStyles, useTheme } from "@mui/styles";
import { Helmet } from "react-helmet";
import { Footer, GlobalSearch, Link, NavBar, usePermissions } from "ui";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCircle,
  faChevronDown,
  faDownload,
  faLaptopCode,
  faQuestionCircle,
  faFileAlt,
  faCommentDots,
  faSquare,
} from "@fortawesome/free-solid-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import { getConfig } from "@ot/config";
import {
  appTitle,
  appDescription,
  appCanonicalUrl,
  externalLinks,
  mainMenuItems,
} from "@ot/constants";
import HomeBox from "./HomeBox";
import Splash from "./Splash";
import Version from "./Version";
import HomePageSuggestions from "./HomePageSuggestions";
import ShouldAccessPPP from "../../components/ShouldAccessPPP";

const config = getConfig();

const useStyles = makeStyles<Theme>(() => ({
  links: {
    marginTop: "12px",
  },
  api: {
    marginTop: "38px",
  },
  dataPolicy: {
    padding: "10px",
    marginTop: "30px",
    border: "2px solid",
    borderColor: config.profile.primaryColor as string,
  },
}));

function AboutPPP(): JSX.Element {
  return (
    <>
      <Typography paragraph>
        The Open Targets Partner Preview Platform is an extension of the Open Targets Platform, a
        comprehensive tool that supports systematic identification and prioritisation of potential
        therapeutic drug targets.
      </Typography>

      <Typography paragraph>
        Combining publicly available datasets with pre-publication data generated by the consortium,
        the Partner Preview Platform builds and scores target-disease associations to assist in drug
        target identification and prioritisation. It also integrates relevant annotation information
        about targets, diseases, phenotypes, and drugs, as well as their most relevant
        relationships.
      </Typography>

      <Typography paragraph>
        The Partner Preview version of the Open Targets Platform is only available to members of the
        Open Targets consortium. It is actively maintained with regular data updates. Data is
        available through an intuitive user interface, and a partner-specific API which includes the
        pre-publication data. The public data is available through data downloads, while
        pre-publication data can be requested through the intranet (home.opentargets.org). The
        pipeline and infrastructure codebases are open-source and the licence allows the creation of
        self-hosted private instances of the Platform with custom data.
      </Typography>
    </>
  );
}

function AboutPublic(): JSX.Element {
  return (
    <>
      <Typography paragraph>
        The E2G Portal enables linking DNA variants to target genes via predictions about enhancer-gene regulatory interactions.
      </Typography>

      <Typography paragraph>
        This portal extends the <Link to="https://platform.opentargets.org" external newTab>Open Targets Platform</Link> with two specific functionalities:
      </Typography>

      <ol>
        <li>
          <strong>Query a variant and find predicted target genes.</strong>  On a variant page, the Enhancer-Gene Predictions table shows predicted enhancers that overlap the query variant. The Variants in Linkage Disequilibrium table shows enhancer overlaps for variants in LD with the query variant.
        </li>
        <li>
          <strong>Browse E2G predictions across cell types.</strong> Visit the <Link to="/igv">genome browser</Link> page to explore enhancer-gene predictions across thousands of cell types and tissues.
        </li>
      </ol>

      <Typography paragraph>
        The rest of the portal’s data and interface are powered by the Open Targets Platform and its API, which are open-source and available on <Link to="https://github.com/opentargets/ot-ui-apps" external>GitHub</Link>.
      </Typography>
    </>
  );
}

interface HelpBoxPanelProps {
  fai: IconDefinition;
  url: string;
  label: string;
  external?: boolean;
}

function HelpBoxPanel({ fai, url, label, external = false }: HelpBoxPanelProps): JSX.Element {
  const theme: Theme = useTheme();
  return (
    <Box
      sx={{
        maxWidth: { md: "150px", xs: "200px" },
      }}
    >
      <Link to={url} external={external}>
        <Box sx={{ gap: 1, display: "flex", flexDirection: "column", alignItems: "center" }}>
          <div className="fa-layers fa-fw fa-6x">
            <FontAwesomeIcon icon={faSquare} color={theme.palette.primary.dark} />
            <FontAwesomeIcon icon={fai} transform="shrink-8" inverse />
          </div>
          <Typography align="center" variant="subtitle1" component="div">
            {label}
          </Typography>
        </Box>
      </Link>
    </Box>
  );
}

const BROWSER_EXAMPLES = [
  {
    label: 'ENCODE-rE2G in 1458 cell types and tissues from ENCODE (Gschwind* et al. 2025)',
    url: 'https://www.biorxiv.org/content/10.1101/2023.11.09.563812v1',
  },
  {
    label: 'scE2G in 46 cell types from cell lines, blood, and pancreas (Sheth*, Qiu* et al. 2025)',
    url: 'https://www.biorxiv.org/content/10.1101/2024.11.23.624931v1',
  },
  {
    label: 'scE2G in 90 cell types from the developing heart (Ma*, Conley* et al. 2025)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/39606363/',
  },
  {
    label: 'scE2G in 10 cell types from the coronary artery (Amrute et al. 2024)',
    url: 'https://www.medrxiv.org/content/10.1101/2024.11.13.24317257v1'
  }
];

function HomePage(): JSX.Element {
  const { isPartnerPreview } = usePermissions();
  const releaseNotesURL = isPartnerPreview
    ? "http://home.opentargets.org/ppp-release-notes"
    : "https://platform-docs.opentargets.org/release-notes";
  const classes = useStyles();

  const handleScrollDown = (): void => {
    window.scrollTo({ top: window.innerHeight, left: 0, behavior: "smooth" });
  };

  return (
    <>
      <ShouldAccessPPP />

      <Helmet title={"E2G"}>
        <meta name="description" content={appDescription} />
        <link rel="canonical" href={appCanonicalUrl} />
      </Helmet>
      <Grid container justifyContent="center" alignItems="center" className={classes.hpSection}>
        <Splash />
        <NavBar name="platform" homepage items={mainMenuItems} placement="bottom-end" />
        <HomeBox>
          <GlobalSearch isHomePage />
          {/* Search examples */}
          <HomePageSuggestions />
          {/* <Version releaseNotesURL={releaseNotesURL} /> */}
          <Divider style={{ marginTop: "25px", marginBottom: "25px" }}>
            <strong>OR</strong>
          </Divider>
          <Typography
              style={{
                marginTop: '25px',
              }}
              align="center"
            >
              Browse enhancer-gene predictions in <Link to="/igv">IGV</Link>:
            </Typography>
            <Grid
              container
              className={classes.examples}
              justifyContent="space-around"
            >
              {BROWSER_EXAMPLES.map((d, i) => (
                <Typography
                  key={i}
                  style={{ textAlign: 'center' }}
                  className={classes.exampleLink}
                  sx={{
                    my: 1,
                  }}
                >
                  <Link to={d.url}>{d.label}</Link>
                </Typography>
              ))}
            </Grid>
        </HomeBox>

        {/* scroll down button */}
        <Grid container justifyContent="center">
          <div
            className="fa-layers fa-fw fa-3x"
            style={{
              height: "0px",
              marginTop: "-1em",
              filter: "drop-shadow( 1px 1px 2px rgba(0, 0, 0, .5))",
              cursor: "pointer",
            }}
            onClick={handleScrollDown}
          >
            <FontAwesomeIcon icon={faCircle} inverse />
            <FontAwesomeIcon icon={faChevronDown} transform="shrink-4" />
          </div>
        </Grid>
      </Grid>

      {/* About */}

      <Grid container justifyContent="center" sx={{ my: 10 }}>
        <Grid item xs={10} md={8} sx={{ my: 2 }}>
          <Typography variant="h4" component="h1" align="center" paragraph mb={5}>
            About the E2G Portal
          </Typography>
          {isPartnerPreview ? <AboutPPP /> : <AboutPublic />}
        </Grid>
      </Grid>

      {/* Get started */}
      {/* <Grid container justifyContent="center" sx={{ mb: 18 }}>
        <Grid item xs={10} md={8}>
          <Typography variant="h4" component="h1" align="center" paragraph mb={5}>
            Get started with the Platform
          </Typography>

          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              gap: { xs: 5, md: 1 },
              alignItems: { xs: "center", md: "flex-start" },
              flexDirection: {
                xs: "column",
                md: "row",
              },
            }}
          >
            <HelpBoxPanel
              fai={faDownload}
              url="/downloads"
              label="Download all of our open datasets"
            />

            <HelpBoxPanel
              fai={faLaptopCode}
              url="/api"
              label="Access data with our GraphQL API"
              external
            />

            <HelpBoxPanel
              fai={faQuestionCircle}
              url="https://platform-docs.opentargets.org/"
              label="Check out our Platform documentation"
              external
            />

            <HelpBoxPanel
              fai={faFileAlt}
              url="https://platform-docs.opentargets.org/citation"
              label="Read our latest Platform publications"
              external
            />

            <HelpBoxPanel
              fai={faCommentDots}
              url="https://community.opentargets.org/"
              label="Join the Open Targets Community"
              external
            />
          </Box>
        </Grid>
      </Grid> */}

      {/* <Footer externalLinks={externalLinks} /> */}
    </>
  );
}

export default HomePage;
